if(LINUX)
    add_compile_definitions(__OS_LINUX__)
elseif(WIN32)
    add_compile_definitions(__WINDOWS_WASAPI__)                
elseif(DARWIN)
    add_compile_definitions(__MACOSX_CORE__)
    find_library(COREAUDIO_LIB CoreAudio)
    find_library(COREFOUNDATION_LIB CoreFoundation)
    list(APPEND LINKLIBS ${COREAUDIO_LIB} ${COREFOUNDATION_LIB})
    list(APPEND LIBS_REQUIRES "-framework CoreAudio -framework CoreFoundation")
    list(APPEND API_DEFS "-D__MACOSX_CORE__")
    list(APPEND API_LIST "core")
endif()
