if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
set ($LINUX 1)
else()
set ($LINUX 0)
endif()
set(MSG ">>> Configure ${PROJECT_NAME} for:")

if(LINUX)
message(STATUS "${MSG} Linux")
add_compile_definitions(__OS_LINUX__)
elseif(WIN32)
message(STATUS "${MSG} Windows")
add_compile_definitions(__OS_WINDOWS__)
    if(MINGW)
        message(STATUS "configure includes for MinGW")        
        LINK_DIRECTORIES(C:/Windows/System32)
    endif()
elseif(DARWIN)
message(STATUS "${MSG} MacOS")
add_compile_definitions(__APPLE__)
add_compile_definitions(__OS_MACOSX__)
else()

endif()
