name: Build MacOS

on:
  push:
    branches:
       - main
       - Improve-CI
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
           brew update
           brew install qt@5 cmake extra-cmake-modules stk
           
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
           cmake -B ${{github.workspace}}/build \
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    - name: Build
      # Build your program with the given configuration
      run: |
           echo "Github workspace=${{github.workspace}}"
           echo "PWD=${PWD}"
           cd ${{github.workspace}}/build
           make
    
    - name: Build Package
      run: |
           cd ${{github.workspace}}/build
           make install
           /usr/local/Cellar/qt@5/5.15.3/bin/macdeployqt tuningTrainer.app
           
    - name: Prepare Artifact
      run: |
           cd ${{github.workspace}}/build
           if [[ -x artifacts ]]; then rmdir -Rf artifacts
           mkdir artifacts
           mv tuningTrainer.app artifacts/tuningTrainer.app
    
    - name: Upload tuningTrainer-mac
      uses: actions/upload-artifact@v3.0.0
      with:
        name: tuningTrainer-macos-monterrey
        path: ${{github.workspace}}/build/artifacts
        
