name: cmake-windows

on:
  push:
    branches:
       - main
       - CI-cmake
  pull_request:
    branches: [ main ]

env:
  #  Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_WORKSPACE: C:\msys64\home\runneradmin

jobs:
  build-windows:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\msys64\usr\bin\bash.exe -leo pipefail {0}

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      
    - name: Print MinGW directory
      shell: cmd
      run: |
           dir C:\msys64\home\runneradmin
      
    - name: View MINGW env vars
      run: |
           echo "$(pwd -W)"
           echo "$(ls -lah)"

    - name: Setup MinGW Build environment
      run: |
           pacman -S --noconfirm --needed base base-devel autoconf automake-wrapper dos2unix zip git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake

    - name: Install qt5
      run: |
           pacman -S --noconfirm --needed mingw-w64-x86_64-qt5

    - name: Build and install stk
      run: |
           cd /home/runneradmin/tuningTrainer/.github/mingw-deps/stk/
           dos2unix PKGBUILD
           makepkg-mingw -si --noconfirm
           cd $MINGW_GIT_WORKSPACE
           pacman -Ql mingw-w64-x86_64-stk

    - name: Build tuningTrainer
      # Build your program with the given configuration
      run: |
           cd /home/runneradmin/tuningTrainer/
           mkdir build
           cd build
           cmake .. \
              -G "Unix Makefiles" \
              -DCMAKE_CXX_FLAGS="-static -I/mingw64/include/stk -isystem /mingw64/include/stk -static -L /mingw64/lib" 
           make

    - name: PackagetuningTrainer
      run: |
           /home/runneradmin/tuningTrainer/.github/scripts/mingw-prepare-package.sh

    - name: Upload tuningTrainer-win.zip
      uses: actions/upload-artifact@v3.0.0
      with:
        name: tuningTrainer-win
        path: ${{github.workspace}}\build\tuningTrainer-win
